namespace CovidAPI.Models
{
    public class Case
    {
        public string Id { get; set; }
        public string region_ce_cases_active { get; set; }
        public string region_ce_cases_confirmed_todate { get; set; }
        public string region_ce_deceased_todate { get; set; }
        public string region_ce_vaccinated_1st_todate { get; set; }
        public string region_ce_vaccinated_2nd_todate { get; set; }
        public string region_foreign_cases_active { get; set; }
        public string region_foreign_cases_confirmed_todate { get; set; }
        public string region_foreign_deceased_todate { get; set; }
        public string region_kk_cases_active { get; set; }
        public string region_kk_cases_confirmed_todate { get; set; }
        public string region_kk_deceased_todate { get; set; }
        public string region_kk_vaccinated_1st_todate { get; set; }
        public string region_kk_vaccinated_2nd_todate { get; set; }
        public string region_kp_cases_active { get; set; }
        public string region_kp_cases_confirmed_todate { get; set; }
        public string region_kp_deceased_todate { get; set; }
        public string region_kp_vaccinated_1st_todate { get; set; }
        public string region_kp_vaccinated_2nd_todate { get; set; }
        public string region_kr_cases_active { get; set; }
        public string region_kr_cases_confirmed_todate { get; set; }
        public string region_kr_deceased_todate { get; set; }
        public string region_kr_vaccinated_1st_todate { get; set; }
        public string region_kr_vaccinated_2nd_todate { get; set; }
        public string region_lj_cases_active { get; set; }
        public string region_lj_cases_confirmed_todate { get; set; }
        public string region_lj_deceased_todate { get; set; }
        public string region_lj_vaccinated_1st_todate { get; set; }
        public string region_lj_vaccinated_2nd_todate { get; set; }
        public string region_mb_cases_active { get; set; }
        public string region_mb_cases_confirmed_todate { get; set; }
        public string region_mb_deceased_todate { get; set; }
        public string region_mb_vaccinated_1st_todate { get; set; }
        public string region_mb_vaccinated_2nd_todate { get; set; }
        public string region_ms_cases_active { get; set; }
        public string region_ms_cases_confirmed_todate { get; set; }
        public string region_ms_deceased_todate { get; set; }
        public string region_ms_vaccinated_1st_todate { get; set; }
        public string region_ms_vaccinated_2nd_todate { get; set; }
        public string region_ng_cases_active { get; set; }
        public string region_ng_cases_confirmed_todate { get; set; }
        public string region_ng_deceased_todate { get; set; }
        public string region_ng_vaccinated_1st_todate { get; set; }
        public string region_ng_vaccinated_2nd_todate { get; set; }
        public string region_nm_cases_active { get; set; }
        public string region_nm_cases_confirmed_todate { get; set; }
        public string region_nm_deceased_todate { get; set; }
        public string region_nm_vaccinated_1st_todate { get; set; }
        public string region_nm_vaccinated_2nd_todate { get; set; }
        public string region_po_cases_active { get; set; }
        public string region_po_cases_confirmed_todate { get; set; }
        public string region_po_deceased_todate { get; set; }
        public string region_po_vaccinated_1st_todate { get; set; }
        public string region_po_vaccinated_2nd_todate { get; set; }
        public string region_sg_cases_active { get; set; }
        public string region_sg_cases_confirmed_todate { get; set; }
        public string region_sg_deceased_todate { get; set; }
        public string region_sg_vaccinated_1st_todate { get; set; }
        public string region_sg_vaccinated_2nd_todate { get; set; }
        public string region_unknown_cases_active { get; set; }
        public string region_unknown_cases_confirmed_todate { get; set; }
        public string region_unknown_deceased_todate { get; set; }
        public string region_za_cases_active { get; set; }
        public string region_za_cases_confirmed_todate { get; set; }
        public string region_za_deceased_todate { get; set; }
        public string region_za_vaccinated_1st_todate { get; set; }
        public string region_za_vaccinated_2nd_todate { get; set; }
    }
}